# Generated by Django 3.0.7 on 2020-07-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcheckout',
            name='cart_items',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
