# Generated by Django 3.0.7 on 2020-07-22 16:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartcheckout_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartcheckout',
            name='cart_items',
            field=jsonfield.fields.JSONField(),
        ),
    ]
