# Generated by Django 3.0.7 on 2020-07-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200722_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartcheckout',
            name='cart_items',
            field=models.CharField(max_length=500),
        ),
    ]
