# Generated by Django 3.0.7 on 2020-07-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200722_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartcheckout',
            name='cart_items',
            field=models.TextField(),
        ),
    ]
