# Generated by Django 3.0.7 on 2020-06-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='marketapp/static/image/')),
                ('cost', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('health', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('rarity', models.CharField(choices=[('FR', 'Free'), ('CO', 'Common'), ('RA', 'Rare'), ('EP', 'Epic'), ('LE', 'Legendary')], max_length=2)),
            ],
        ),
    ]
