# Generated by Django 3.0.7 on 2020-06-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0004_auto_20200622_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='hero_class',
            field=models.CharField(choices=[('DR', 'Druid'), ('HU', 'Hunter'), ('MA', 'Mage'), ('PA', 'Paladin'), ('PR', 'Priest'), ('RO', 'Rogue'), ('SH', 'Shaman'), ('WL', 'Warlock'), ('WA', 'Warrior'), ('CC', 'Common')], default='', max_length=2),
        ),
    ]
