# Generated by Django 3.0.7 on 2020-06-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0005_auto_20200622_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='marketapp/static/marketapp/'),
        ),
    ]
