# Generated by Django 3.0.7 on 2020-06-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0006_auto_20200622_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('FR', 'Free'), ('CO', 'Common'), ('RA', 'Rare'), ('EP', 'Epic'), ('LE', 'Legendary')], default='', max_length=2),
        ),
    ]
