# Generated by Django 3.0.7 on 2020-06-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0007_auto_20200623_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_set',
            new_name='set',
        ),
    ]
