# Generated by Django 3.0.7 on 2020-07-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0008_auto_20200624_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(default='new-card', max_length=50),
        ),
    ]
