# Generated by Django 3.0.7 on 2020-07-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0009_auto_20200701_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
