# Generated by Django 3.0.7 on 2020-07-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0010_auto_20200701_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='set',
            new_name='card_set',
        ),
    ]
