# Generated by Django 3.0.7 on 2020-07-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0014_auto_20200716_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='title',
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.FloatField(),
        ),
    ]
